name: Tests

on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - src/**
      - tests/**
      - requirements.txt
      - requirements_dev.txt
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test:
    name: Testing ğŸ§ª
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setting up Python ${{ matrix.python-version }} ğŸ
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies ğŸ“¥
        run: |
          python3 -m pip install --upgrade pip
          pip install -e .
          pip install tox tox-gh-actions
      - name : Running Tox â–¶ï¸
        run: tox -v
      - name: Upload test coverage to Codecov â˜‚ï¸
        uses: codecov/codecov-action@v3
        with:
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON

  types:
    name: Static types checking ğŸ”
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setting up Python ğŸ
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Installing dependencies ğŸ“¥
        run: |
          python3 -m pip install --upgrade pip
          pip install mypy types-colorama
      - name: Running MyPy â–¶ï¸
        run: mypy src/failures/

  style:
    name: Code style checking ğŸ¨
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setting up Python ğŸ
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Installing dependencies ğŸ“¥
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8
      - name: Running flake8 â–¶ï¸
        run: flake8 src/failures/