name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Testing ğŸ§ª
    runs-on: ubuntu-latest

    env:
      os: ubuntu-latest
      python-version: 3.11
      package: failures

    steps:
      - uses: actions/checkout@v3
      - name: Setting up Python ${{ env.python-version }} ğŸ
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python-version }}
      - name: Installing dependencies ğŸ“¥
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest pytest-sugar pytest-cov
      - name : Running PyTest â–¶ï¸
        run: pytest --cov ${{ env.package }} tests
      - name: Upload test coverage to Codecov â˜‚ï¸
        uses: codecov/codecov-action@v3
        with:
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: os,python-version

  types:
    name: Static types checking ğŸ”
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
      - name: Setting up Python ${{ env.python-version }} ğŸ
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python-version }}
      - name: Installing dependencies ğŸ“¥
        run: |
          python3 -m pip install --upgrade pip
          pip install mypy
      - name: Running MyPy â–¶ï¸
        run: mypy --install-types --non-interactive ${{ env.package }}

  style:
    name: Code style checking ğŸ¨
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
      - name: Setting up Python ${{ env.python-version }} ğŸ
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python-version }}
      - name: Installing dependencies ğŸ“¥
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8
      - name: Running flake8 â–¶ï¸
        run: flake8 ${{ env.package }}
